[package]
name = "rewrite-root"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rewrite-impl = { path = "../impl" }

[dev-dependencies]
sqlx = { version = "0.7", features = ["sqlite"] }
